config/routes.rb
Rails.application.routes.draw do

  root 'app#home'
  get '/printers' => 'app#printer'
  get '/mfu' => 'app#mfu'
  get '/scanners' => 'app#scanner'
  get '/paper' => 'app#paper'
  get '/shredders' => 'app#shredder'
  get '/cartridges' => 'app#cartridge'
  get '/laminators' => 'app#laminator'
  get '/bookbinders' => 'app#bookbinder'
  get '/other' => 'app#other'
  get '/search' => 'app#search'
  get '/help' => 'app#help'

  get 'user/(:id)' => 'user#show'
  get 'user/(:id)/edit' => 'user#edit'
  patch 'user/(:id)/edit' => 'user#update'
  get 'signup' => 'user#new'
  post 'signup' => 'user#create'

  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'

  get 'cart/(:id)' => 'cart#show'
  get 'cart/(:id)/process' => 'cart#info'
  post 'cart/(:id)/process' => 'cart#submit'

  get 'item/(:id)' => 'item#show'
  post 'item/(:id)/add' => 'item#add'
  post 'item' => 'item#create'
  patch 'item/(:id)' => 'item#edit'
  delete 'item/(:id)' => 'item#destroy'
  delete 'cart_item/(:id)' => 'cart_item#destroy'
  delete 'cart_items/(:id)' => 'cart_item#remove'
  post 'cart_item/(:id)' => 'cart_item#add'
  post 'feedback/(:id)' => 'item#rate'
  get 'feedback/(:id)/edit' => 'admin#feededit'

  get 'admin' => 'admin#index'
  get 'admin/(:id)' => 'admin#show'
  patch 'feedback/(:id)' => 'admin#feedupdate'
  delete 'feedback/(:id)' => 'admin#feeddestroy'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	
	def new
		render 'new'
	end

	def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      if user.activated?
        log_in user
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        redirect_to user
      else
        message  = "Account not activated. "
        message += "Check your email for the activation link."
        flash[:warning] = message
        log_in user
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        redirect_to user
      end
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

	def destroy
		log_out
		redirect_to root_url
	end

end

app/helpers/session_helper.rb
module SessionHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
    cookies.permanent[:log_cart] ||= Cart.create(user_id: user.id).id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
  	forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def has_data?
    return false if !logged_in?
    !current_user.address.nil? && !current_user.number.nil?
  end

  def is_admin?
    return false if current_user.nil?
    current_user.id == 1
  end

end

app/views/session/new.html.erb
<br/><br/>
<script src="https://use.fontawesome.com/476a805558.js"></script>
<div class="col-md-4 col-md-offset-4">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Войти как покупатель</h3>
    </div>
    <div id="existing-customer" class="panel-body" data-hook="login">
      <% if @error %>
        <div class="alert alert-danger">
          <%= @error %>
        </div>
      <% end %>
      
      <%= form_tag "/login", method: :post do %>
        <fieldset id="password-credentials">
          <div class="form-group">
            <input class="form-control" tabindex="1" placeholder="Электронная почта" type="email" name="session[email]"/>
          </div>
          <div class="form-group">
            <input class="form-control" tabindex="2" placeholder="Пароль" type="password" name="session[password]"/>
          </div>
          <div class="checkbox">
              <input name="session[remember_me]" type="hidden" value="0" />
              <input type="checkbox" id="remember_me" value="1" name="session[remember_me]"/>
              <label for="remember_me">Запомнить меня</label>
          </div>
          <%= submit_tag("Войти", class: 'btn btn-inverse btn-large btn-block') %>
        </fieldset>
      <% end %>
      <div class="text-center">
        или 
        <a href="/signup">Создать новую учетную запись</a> |
        <a href="<%= new_password_reset_path %>">Забыли пароль?</a>
      </div>
    </div>
  </div>
</div>