config/routes.rb
Rails.application.routes.draw do

  root 'app#home'
  get '/printers' => 'app#printer'
  get '/mfu' => 'app#mfu'
  get '/scanners' => 'app#scanner'
  get '/paper' => 'app#paper'
  get '/shredders' => 'app#shredder'
  get '/cartridges' => 'app#cartridge'
  get '/laminators' => 'app#laminator'
  get '/bookbinders' => 'app#bookbinder'
  get '/other' => 'app#other'
  get '/search' => 'app#search'
  get '/help' => 'app#help'

  get 'user/(:id)' => 'user#show'
  get 'user/(:id)/edit' => 'user#edit'
  patch 'user/(:id)/edit' => 'user#update'
  get 'signup' => 'user#new'
  post 'signup' => 'user#create'

  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'

  get 'cart/(:id)' => 'cart#show'
  get 'cart/(:id)/process' => 'cart#info'
  post 'cart/(:id)/process' => 'cart#submit'

  get 'item/(:id)' => 'item#show'
  post 'item/(:id)/add' => 'item#add'
  post 'item' => 'item#create'
  patch 'item/(:id)' => 'item#edit'
  delete 'item/(:id)' => 'item#destroy'
  delete 'cart_item/(:id)' => 'cart_item#destroy'
  delete 'cart_items/(:id)' => 'cart_item#remove'
  post 'cart_item/(:id)' => 'cart_item#add'
  post 'feedback/(:id)' => 'item#rate'
  get 'feedback/(:id)/edit' => 'admin#feededit'

  get 'admin' => 'admin#index'
  get 'admin/(:id)' => 'admin#show'
  patch 'feedback/(:id)' => 'admin#feedupdate'
  delete 'feedback/(:id)' => 'admin#feeddestroy'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/views/layouts/_address.html.erb
<div class="well">
	<div class="form-group">
		<input class="form-control" tabindex="1" pattern="^[А-я ]+$" data-error="Неверное имя города" placeholder="Город" type="text" name="city"/>
		<div class="help-block with-errors"></div>
	</div>
	<div class="form-inline">
		<div class="form-group">
			<input class="form-control" size="30" tabindex="1" pattern="^[А-я -]+$" data-error="Неверное имя улицы" placeholder="Улица" type="text" name="street"/>
			<div class="help-block with-errors"></div>
		</div>
		<div class="form-group">
			<input class="form-control" size="10" tabindex="1" pattern="^\d+$" data-error="Неверный номер дома" placeholder="Дом" type="text" name="building"/>
			<div class="help-block with-errors"></div>
		</div>
		<div class="form-group">
			<input class="form-control" size="10" tabindex="1" pattern="^\d+$" data-error="Неверный номер квартиры" placeholder="Квартира" type="text" name="flat"/>
			<div class="help-block with-errors"></div>
		</div>
	</div>
</div>

app/views/layouts/_error_msg.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_filters.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
<script>
	$( function() {
	$( "#slider-range" ).slider({
	  range: true,
	  min: <%= @min %>,
	  max: <%= @max %>,
	  values: [ <%= @min %>, <%= @max %> ],
	  slide: function( event, ui ) {
	    $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
	  }
	});
	$( "#amount" ).val( $( "#slider-range" ).slider( "values", 0 ) +
	  " тг. - " + $( "#slider-range" ).slider( "values", 1 ) + " тг." );
	});
</script>
<div>
	<%= form_tag request.original_url, method: :get do %>
		<p>
		  <label for="amount">Диапазон:</label>
		  <input type="text" name="range" id="amount" readonly style="border:0; color:#000000; font-weight:bold;">
		</p>
		<div id="slider-range"></div>
		<br>
		<%= submit_tag "Фильтровать", class: "btm btn-block btn-large btn-inverse" %>
	<% end %>
</div>

app/views/layouts/_footer.html.erb
<br>
<footer class="black footer">
	<div class="container">
	<div class="row" style="padding-top: 5px;">
		<div class="col-md-3">
			<ul class="footer" style="list-style-type:none">
					<li><a href="/help#company">О нас</a></li>
					<li><a href="/help#jobs">Вакансии</a></li>
					<li><a href="/help#contacts">Контакты</a></li>
					<li><a href="http://www.techcentre.kz/">Techcentre.kz</a></li>
					<br/><br/>
					<li>ТОО "ТехЦентр" (с)2016</li>
			</ul>
		</div>
		<div class="col-md-4">
			<table style="margin-bottom: 5px;">
	    		<div class="text-left" style="font-size: 18px; color: #aaaaaa;">Контактная информация</div>
	    		<hr>
				<tr><td colspan="2" style="color: #aaaaaa;"><b>Офис в Алматы</b> ул. Абылай Хана 56</td></tr>
				<tr><td style="color: #aaaaaa;"><b>Тел.</b> 8(727) 273-84-82&nbsp&nbsp&nbsp&nbsp&nbsp</td><td style="color: #aaaaaa;"><b>Факс</b> 8(727) 273-84-82</td></tr>		
			</table>

			<table style="margin-bottom: 5px;">
				<tr><td colspan="2" style="color: #aaaaaa;"><b>Офис в Астане</b> пр. Туран 9</td></tr>
				<tr><td style="color: #aaaaaa;"><b>Тел.</b> 8(727) 273-84-82&nbsp&nbsp&nbsp&nbsp&nbsp</td><td style="color: #aaaaaa;"><b>Факс</b> 8(727) 273-84-82</td></tr>
			</table>
			<table>
				<tr><td style="color: #aaaaaa;"><b>Эл. почта:</b> info@techcentre.kz</td></tr>
				<tr><td style="color: #aaaaaa;"><b>ICQ:</b> 614700692</td></tr>
			</table>
		</div>
		<div class="col-md-5">
			<table>
				<div class="text-left" style="font-size: 18px; color: #aaaaaa;">Интернет-магазин "Техцентр"</div>	
				<hr>
				<tr><td style="color: #676767;">В интернет-магазине "Техцентр" вы можете приобрести принтеры, сканеры, мфу, шредеры, ламинаторы, переплётные машины и другую оргтехнику, а также расходные материалы, бумагу и картриджи для принтеров от компаний Xerox, Konica и Mondi. Вы можете заказать доставку или забрать товар самовывозом. На сайте всегда указаны актуальные цены.</td></tr>
			</table>
		</div>
	</div>

	</div>
</footer>

app/views/layouts/_head.html.erb
<title>Techcenter</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<style type="text/css">
.badge-warning {
  background-color: #f89406;
}

</style>

app/views/layouts/_header.html.erb
<header class="black">
	<div class="container flexible-header">
		<div><a href="/"><%= image_tag "logo.png" %></a></div>
		<div style="margin-top: 1em;" class="row">
			<form class="form-search" action="/search">
				<div class="input-prepend">
					<button type="submit" class="btn"><%= image_tag "search.png", size: "15x15" %></button>
					<input type="text" class="sfield search-query" placeholder="Поиск" name="req">
				</div>
			</form>
		</div>
		<div class="hidden-xs hidden-sm">
		<% if logged_in? %>
				<%= link_to cart_url(cookies.permanent[:log_cart]), class: "header" do %>
					<div class="header">
						В корзине&nbsp&nbsp
						<span class="badge badge-warning"><%= CartItem.where(cart_id: cookies.permanent[:log_cart]).count %></span>
						&nbsp
					    <%= image_tag('cart.png') %>
					</div>
				<% end %>		
		<% else %>
			<%= link_to cart_url(cookies.permanent[:stgr_cart]), class: "header" do %>
					<div class="header">
						В корзине&nbsp&nbsp
						<span class="badge"><%= CartItem.where(cart_id: cookies.permanent[:stgr_cart]).count %></span>
						&nbsp
					    <%= image_tag('cart.png') %>
					  
					</div>
				<% end %>
		<% end %>
		</div>
		<a href="/help" class="header"><div class="hidden-xs hidden-sm header">Помощь&nbsp<%= image_tag "help.png" %></div></a>
		<% if logged_in? %>
			<%= link_to user_url(current_user), class: "header" do %>
				<div class="hidden-xs hidden-sm header">
			    <%= current_user.name %>&nbsp<%= image_tag('user.png') %>
			    </div>
			<% end %>
		<% else %>
			<a href="/login" class="header"><div class="hidden-xs hidden-sm header">Логин&nbsp&nbsp<%= image_tag "user.png" %></div></a>
		<% end %>
	</div>
</header>

app/views/layouts/_navbar.html.erb
<br/>
	<table class="table table-hover table-inverse">
		<tr>
			<td><a href="/printers">Принтеры</a></td>
		</tr>
		<tr>
			<td><a href="/mfu">МФУ</a></td>
		</tr>
		<tr>
			<td><a href="/scanners">Сканеры</a></td>
		</tr>
		<tr>
			<td><a href="/paper">Бумага</a></td>
		</tr>
		<tr>
			<td><a href="/cartridges">Картриджи</a></td>
		</tr>
		<tr>
			<td><a href="/shredders">Шредеры</a></td>
		</tr>
		<tr>
			<td><a href="/laminators">Ламинаторы</a></td>
		</tr>
		<tr>
			<td><a href="/bookbinders">Переплётные машины</a></td>
		</tr>	
		<tr>
			<td><a href="/other">Расходные материалы</a></td>
		</tr>
	</table>

app/views/layouts/_number.html.erb
<div class="form-group">
	<input class="form-control" tabindex="1" placeholder="Номер телефона" type="text" pattern="^\d{10}$" data-error="Неверный номер, убедитесь, что ввели последние 10 цифр номера" name="number"/>
	<div class="help-block with-errors"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/head' %>
</head>
<body>
	<%= render 'layouts/header' %>
	
	<div class="container">
		<%= yield %>
	</div>

	<%= render 'layouts/footer' %>
</body>
</html>